[tool.poetry]
name = "hexlet-code"
version = "0.1.0"
description = ""
authors = ["Krusovice kickstar69@yandex.ru"]
readme = "README.md"
packages = [
  { include = "gendiff" },
]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.scripts]
diff = 'scripts.gendiff:generate_diff'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
